# docker-compose.yml
version: "3"
services:
  fastapi:
    container_name: fastapi_board
    ports:
      - "8000:8000"
    image: fastapi_board:v1
    environment:
      - DATABASE_URL=postgresql://developer:devpassword@postgres:5432/developer
      - REDIS_URL=redis://redis:6379
      - SESSION_SECRET=IdwJ9b6B9gBitU8HQc3-Lv5eN9XbC40qmdtmps7xDRY=

  postgres:
    container_name: fastapi_board_postgres
    image: postgres:15.5-alpine
    environment:
      - POSTGRES_DB=developer
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=devpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:25000:5432"
  redis:
    container_name: fastapi_board_redis
    image: redis:7.2.3-alpine3.18
    ports:
      - "127.0.0.1:25100:6379"
    command: redis-server --save ""

volumes:
  postgres-data:
    driver: local
